import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <SidebarProvider className="grid grid-cols-[200px_auto] grid-rows-12">
            <div className="row-span-full">
              <AppSidebar />
            </div>
            <div className="col-span-1 mt-2">
              <Navbar />
              <div className="">{children}</div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
      <script src="https://kit.fontawesome.com/44b694a7ec.js" async></script>
    </html>
  );
}
